services:
  db:
    image: postgres:15.3
    container_name: inertia-chat-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inertia_chat
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d inertia_chat"]
      interval: 5s
      timeout: 5s
      retries: 5

  dbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: inertia-chat-dbeaver
    ports:
      - "8978:8978"
    volumes:
      - dbeaver_data:/opt/dbeaver/workspace
    restart: unless-stopped

volumes:
  db_data:
  dbeaver_data: