@baseUrl = {{$dotenv API_BASE_URL}}
@contentType = application/json
@cookieJar = api/auth

### Login
# @name login
POST {{baseUrl}}/auth/login
Content-Type: {{contentType}}

{
  "emailOrUsername": "testuser",
  "password": "password123"
}

### Find existing 1:1 chat with another user
# Replace {userId} with the actual user ID you want to chat with
GET {{baseUrl}}/chats/with/1
Authorization: Bearer {{login.response.body.data.accessToken}}

### Create new 1:1 chat with another user
# Replace {userId} with the actual user ID you want to chat with
POST {{baseUrl}}/chats/with/1
Authorization: Bearer {{login.response.body.data.accessToken}}

### Get all chats for current user
GET {{baseUrl}}/chats
Authorization: Bearer {{login.response.body.data.accessToken}}

### Delete chat
DELETE {{baseUrl}}/chats/4
Authorization: Bearer {{login.response.body.data.accessToken}}