@baseUrl = {{$dotenv API_BASE_URL}}
@contentType = application/json
@cookieJar = api/auth

### Login
# @name login
POST {{baseUrl}}/auth/login
Content-Type: {{contentType}}

{
  "emailOrUsername": "anas",
  "password": "password123"
}

### Get all users except current user
GET {{baseUrl}}/users
Authorization: Bearer {{login.response.body.data.accessToken}}

### Get current user profile
GET {{baseUrl}}/users/me
Authorization: Bearer {{login.response.body.data.accessToken}}

### Update user status
PATCH {{baseUrl}}/users/me/status
Content-Type: {{contentType}}
Authorization: Bearer {{login.response.body.data.accessToken}}

{
    "status": "OFFLINE"
}

### Update user profile
# @name updateProfile
PUT {{baseUrl}}/users/me
Content-Type: {{contentType}}
Authorization: Bearer {{login.response.body.data.accessToken}}

{
    "name": "Ahmed",
    "username": "ahmed",
    "profilePicture": "https://i.pravatar.cc/150?img=2"
}

### Delete user profile
POST {{baseUrl}}/users/me/delete
Content-Type: {{contentType}}
Authorization: Bearer {{login.response.body.data.accessToken}}

{
    "password": "password123"
}